apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-jenkins
  namespace: argocd
spec:
  destination:
    namespace: ci-cd
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: jenkins
    helm:
      valueFiles:
      - values.yaml
    repoURL: https://sgoser.github.io/helm/
    targetRevision: 0.3.0
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true