---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-simpleweb
  namespace: argocd
spec:
  destination:
    namespace: simpleweb
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./
    repoURL: https://github.com/sgoser/k3s.simpleweb.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
